#!/bin/bash
shopt -s expand_aliases

# Create alias if necessary for backwards compatiblity
MYSQL_BIN=/usr/local/mariadb/columnstore/mysql/bin/mysql
if test -f "$MYSQL_BIN"; then
  alias mariadb="/usr/local/mariadb/columnstore/mysql/bin/mysql --defaults-extra-file=/usr/local/mariadb/columnstore/mysql/my.cnf -u root"
fi

# Set some variables
ANALYTICS_ONLY="${ANALYTICS_ONLY:-0}"
USE_S3_STORAGE="${USE_S3_STORAGE:-0}"
CAP_PCT=99 #(0-99)
CS_CONFIG=/etc/my.cnf.d/columnstore.cnf
FLAG=/etc/columnstore/container-initialized
LOG_PREFIX=/var/log/mariadb/columnstore
MAX_RAM=$( free -mt | awk 'NR==4{printf "%d", $2*.'$CAP_PCT' }' )
MCS_INSTALL_BIN=/usr/bin
MCS_INSTALL_PATH=/var/lib/columnstore
NUMBLOCKSPCT=$( echo $MAX_RAM / 2  | bc )M
SERVER_ID=$( hostname -i | cut -d "." -f 4 )
TOTALUMMEMORY=$( echo $MAX_RAM / 4  | bc )M

# postConfigure function
run_postConfigure()
{
    postConfigureParameter="-x -xr -numBlocksPct $NUMBLOCKSPCT -totalUmMemory $TOTALUMMEMORY"
    if [ $USE_S3_STORAGE -eq 1 ]; then
        echo -e "1\n\n4\n1\n" | $MCS_INSTALL_BIN/postConfigure $postConfigureParameter
    else
        $MCS_INSTALL_BIN/postConfigure -qs $postConfigureParameter
    fi
    if [ 0 -eq $? ]; then
        echo "Installation successful."
    else
        echo "ERROR: postConfigure crashed with exit code $?"
        exit 1
    fi
}

# Set server id if ColumnStore version 1.4 and above
if test -f "$CS_FILE"; then
  sed -i "s|server-id=.*|server-id=$SERVER_ID|" $CS_CONFIG
fi

# Configure storagemanager
if [ $USE_S3_STORAGE -eq 1 ]; then
  sed -i "s|\${HOME}|/var/lib/columnstore|" /etc/columnstore/storagemanager.cnf
  sed -i "s|cache_size = 2g|cache_size = 8g|" /etc/columnstore/storagemanager.cnf
  sed -i "s|service =.*|service = S3|" /etc/columnstore/storagemanager.cnf
  sed -i "s|region =|# region =|" /etc/columnstore/storagemanager.cnf
  sed -i "s|bucket =.*|bucket = $S3_BUCKET|" /etc/columnstore/storagemanager.cnf
  sed -i "s|# endpoint =.*|endpoint = $S3_ENDPOINT|" /etc/columnstore/storagemanager.cnf
  sed -i "s|# aws_access_key_id =.*|aws_access_key_id = $S3_ACCESS_KEY_ID|" /etc/columnstore/storagemanager.cnf
  sed -i "s|# aws_secret_access_key =.*|aws_secret_access_key = $S3_SECRET_ACCESS_KEY|" /etc/columnstore/storagemanager.cnf
fi

# Set Instance Type
if [ $ANALYTICS_ONLY -eq 1 ]; then
  echo "" >> /etc/my.cnf.d/columnstore.cnf
  echo "default_storage_engine=Columnstore" >> /etc/my.cnf.d/columnstore.cnf
  echo "enforce_storage_engine=Columnstore" >> /etc/my.cnf.d/columnstore.cnf
fi

# Start ColumnStore unless this is the first run, in which case we will do postConfigure first
if [ -e $FLAG ]; then
    $MCS_INSTALL_BIN/columnstore start
else
  # Run postConfigure
  run_postConfigure

  MARIADB_RUNNING=$(ps -ef | grep -v grep | grep -v mysqld_safe | grep mysqld | wc -l)
  if [ $MARIADB_RUNNING -gt 0 ]; then

    # Get version
    MARIADB_VERSION=$( mariadb -Ns -e "SELECT LEFT(VERSION(),4);" )

    # Prepare system
    if (( $(echo "$MARIADB_VERSION > 10.3" | bc -l) )); then
      mariadb -e "UNINSTALL PLUGIN simple_password_check;"
    fi
    mariadb -e "DELETE FROM mysql.user WHERE user = ''; DROP DATABASE IF EXISTS test;"
    if [ $? -ne 0 ]; then
        echo "ERROR: During preparing system."
        exit 1
    fi

    # Create Cross Engine Join user account
    CEJ_PASSWORD="'"
    while [[ $CEJ_PASSWORD != *[[:lower:]]* ]] || \
          [[ $CEJ_PASSWORD != *[[:upper:]]* ]] || \
          [[ $CEJ_PASSWORD != *[0-9]* ]] || \
          [[ $CEJ_PASSWORD == */* ]] || \
          [[ $CEJ_PASSWORD != *=* ]]; do
            CEJ_PASSWORD="$(openssl rand -base64 20)"
    done
    mariadb -e "GRANT SELECT ON *.* TO 'cej'@'127.0.0.1' IDENTIFIED BY '$CEJ_PASSWORD';"
    if [ $? -ne 0 ]; then
        echo "ERROR: During cross engine join user creation."
        exit 1
    fi
  $MCS_INSTALL_BIN/mcsSetConfig CrossEngineSupport User "cej"
  $MCS_INSTALL_BIN/mcsSetConfig CrossEngineSupport Password "$CEJ_PASSWORD"
  echo "Cross engine join user created"
  unset CEJ_PASSWORD

    # Add custom host for root user
    if [ $MARIADB_ROOT_HOST ]; then
      mariadb -e "CREATE USER 'root'@'$MARIADB_ROOT_HOST';
                  GRANT ALL PRIVILEGES ON *.* TO 'root'@'$MARIADB_ROOT_HOST' WITH GRANT OPTION;"
        if [ $? -ne 0 ]; then
          echo "ERROR: During 'root'@'$MARIADB_ROOT_HOST' creation."
          exit 1
        fi
    fi

    # Add custom password for root user
    if [ $MARIADB_ROOT_PASSWORD ]; then
        mariadb -Ns -e "SELECT host from mysql.user WHERE user = 'root'" | while read host; do
        mariadb -e "ALTER USER 'root'@'$host' IDENTIFIED BY '$MARIADB_ROOT_PASSWORD';"
      done
      if [ $? -ne 0 ]; then
        echo "ERROR: During root password update."
        exit 1
      fi
      unset MARIADB_ROOT_PASSWORD
    fi

  # Throw error if MariaDB is not running
  else
    echo "ERROR: MariaDB is not running, cannot create cross engine join user."
    exit 1
  fi

  # Create flag file on first run
  touch $FLAG

  # Restart ColumnStore after postConfigure and allow config changes to take place
  $MCS_INSTALL_BIN/mcsadmin restartSystem y

fi
exit 0
